baseurl = "http://ng2-info.github.io/"
languageCode = "ja-jp"
title = "Angular2 Info"
theme = "casper"

[params]
  description = "Angular2の最新情報を不定期更新！"
  cover = "missing.png"
  author = "laco"
  logo = "img/ng2-info.png"
  googleAnalyticsUserID = "UA-52362663-3"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  # githubName = "ng2-info"
  # twitterName = "laco0416"
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false

[permalinks]
  post = "/:year/:month/:filename/"

[blackfriday]
  angledQuotes = false
  fractions = false
  hrefTargetBlank = true
  plainIDAnchors = true
  extensions = ["hardLineBreak"]

[[menu.main]]
  name = "Top"
  weight = -500
  identifier = "index"
  url = "/"

[[menu.main]]
  name = "Tags"
  weight = -150
  identifier = "tags"
  url = "/tags"

[[menu.main]]
  name = "Repository"
  weight = -120
  identifier = "repo"
  url = "https://github.com/ng2-info/ng2-info.github.io"

[[menu.main]]
  name = "Author's Blog"
  weight = -110
  identifier = "blog"
  url = "http://blog.lacolaco.net"
