# Header
menu:
  Home: /
  Archives: /archives
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# Miscellaneous
google_analytics: UA-52362663-3
favicon: /favicon-32x32.png
twitter:
google_plus:
fb_admins:
fb_app_id:

subtitle: Angular2の最新情報を不定期更新！
logo: /ng2-info.png